export const dados = [
    {
        agrupamento: 1,
        nDoc: "0001",
        contato: "Bruno Arruda Magalhães",
        valor: 100.0,
        vencimento: new Date("2023-01-16"),
        descricao: "Uma certa dívida",
        grupo: "Grupo A",
        subgrupo: "Subgrupo B",
        parcela: 1,
        "total-parcelas": 12,
        tipo: "Tipo X",
        "data-baixa": new Date("2023-01-15"),
        "valor-pago": 50.0
      },
      {
        agrupamento: 1,
        nDoc: "0002",
        contato: "Bruno Arruda Magalhães",
        valor: 100.0,
        vencimento: new Date("2023-02-16"),
        descricao: "Uma certa dívida",
        grupo: "Grupo A",
        subgrupo: "Subgrupo B",
        parcela: 2,
        "total-parcelas": 12,
        tipo: "Tipo X",
        "data-baixa": new Date("2023-02-17"),
        "valor-pago": 50.0
      },
      {
        agrupamento: 1,
        nDoc: "0003",
        contato: "Bruno Arruda Magalhães",
        valor: 100.0,
        vencimento: new Date("2023-03-16"),
        descricao: "Uma certa dívida",
        grupo: "Grupo A",
        subgrupo: "Subgrupo B",
        parcela: 3,
        "total-parcelas": 12,
        tipo: "Tipo X",
        "data-baixa": new Date("2023-03-16"),
        "valor-pago": 50.0
      },
      {
        agrupamento: 1,
        nDoc: "0004",
        contato: "Bruno Arruda Magalhães",
        valor: 100.0,
        vencimento: new Date("2023-04-16"),
        descricao: "Uma certa dívida",
        grupo: "Grupo A",
        subgrupo: "Subgrupo B",
        parcela: 4,
        "total-parcelas": 12,
        tipo: "Tipo X",
        "data-baixa": null,
        "valor-pago": null
      },
      {
        agrupamento: 1,
        nDoc: "0005",
        contato: "Bruno Arruda Magalhães",
        valor: 100.0,
        vencimento: new Date("2023-05-16"),
        descricao: "Uma certa dívida",
        grupo: "Grupo A",
        subgrupo: "Subgrupo B",
        parcela: 5,
        "total-parcelas": 12,
        tipo: "Tipo X",
        "data-baixa": null,
        "valor-pago": null
      },
      {
        agrupamento: 1,
        nDoc: "0006",
        contato: "Bruno Arruda Magalhães",
        valor: 100.0,
        vencimento: new Date("2023-06-16"),
        descricao: "Uma certa dívida",
        grupo: "Grupo A",
        subgrupo: "Subgrupo B",
        parcela: 6,
        "total-parcelas": 12,
        tipo: "Tipo X",
        "data-baixa": null,
        "valor-pago": null
      },
      {
        agrupamento: 1,
        nDoc: "0007",
        contato: "Bruno Arruda Magalhães",
        valor: 100.0,
        vencimento: new Date("2023-07-16"),
        descricao: "Uma certa dívida",
        grupo: "Grupo A",
        subgrupo: "Subgrupo B",
        parcela: 7,
        "total-parcelas": 12,
        tipo: "Tipo X",
        "data-baixa": null,
        "valor-pago": null
      },
      {
        agrupamento: 1,
        nDoc: "0008",
        contato: "Bruno Arruda Magalhães",
        valor: 100.0,
        vencimento: new Date("2023-08-16"),
        descricao: "Uma certa dívida",
        grupo: "Grupo A",
        subgrupo: "Subgrupo B",
        parcela: 8,
        "total-parcelas": 12,
        tipo: "Tipo X",
        "data-baixa": null,
        "valor-pago": null
      },
      {
        agrupamento: 1,
        nDoc: "0009",
        contato: "Bruno Arruda Magalhães",
        valor: 100.0,
        vencimento: new Date("2023-09-16"),
        descricao: "Uma certa dívida",
        grupo: "Grupo A",
        subgrupo: "Subgrupo B",
        parcela: 9,
        "total-parcelas": 12,
        tipo: "Tipo X",
        "data-baixa": null,
        "valor-pago": null
      },
      {
        agrupamento: 1,
        nDoc: "0010",
        contato: "Bruno Arruda Magalhães",
        valor: 100.0,
        vencimento: new Date("2023-10-16"),
        descricao: "Uma certa dívida",
        grupo: "Grupo A",
        subgrupo: "Subgrupo B",
        parcela: 10,
        "total-parcelas": 12,
        tipo: "Tipo X",
        "data-baixa": null,
        "valor-pago": null
      },
      {
        agrupamento: 1,
        nDoc: "0011",
        contato: "Bruno Arruda Magalhães",
        valor: 100.0,
        vencimento: new Date("2023-11-16"),
        descricao: "Uma certa dívida",
        grupo: "Grupo A",
        subgrupo: "Subgrupo B",
        parcela: 11,
        "total-parcelas": 12,
        tipo: "Tipo X",
        "data-baixa": null,
        "valor-pago": null
      },
      {
        agrupamento: 1,
        nDoc: "0012",
        contato: "Bruno Arruda Magalhães",
        valor: 100.0,
        vencimento: new Date("2023-12-16"),
        descricao: "Uma certa dívida",
        grupo: "Grupo A",
        subgrupo: "Subgrupo B",
        parcela: 12,
        "total-parcelas": 12,
        tipo: "Tipo X",
        "data-baixa": null,
        "valor-pago": null
      }
]