export const dados = [
    {
        id: 1,
        agrupamento: 1,
        nDoc: "0001",
        contato: "Bruno Arruda Magalhães",
        responsavel: "Susanna Sarah Cordeiro Paulino",
        valor: 100.0,
        vencimento: "2023-01-16",
        descricao: "Uma certa dívida",
        grupo: "Grupo A",
        subgrupo: "Subgrupo B",
        parcela: 1,
        tParcelas: 12,
        tipo: "D",
        dBaixa: "2023-01-15",
        pago: 50.0
      },
      {
        id: 2,
        agrupamento: 1,
        nDoc: "0002",
        contato: "Bruno Arruda Magalhães",
        responsavel: "Susanna Sarah Cordeiro Paulino",
        valor: 100.0,
        vencimento: "2023-02-16",
        descricao: "Uma certa dívida",
        grupo: "Grupo A",
        subgrupo: "Subgrupo B",
        parcela: 2,
        tParcelas: 12,
        tipo: "D",
        dBaixa: "2023-02-17",
        pago: 50.0
      },
      {
        id: 3,
        agrupamento: 1,
        nDoc: "0003",
        contato: "Bruno Arruda Magalhães",
        responsavel: "Susanna Sarah Cordeiro Paulino",
        valor: 100.0,
        vencimento: "2023-03-16",
        descricao: "Uma certa dívida",
        grupo: "Grupo A",
        subgrupo: "Subgrupo B",
        parcela: 3,
        tParcelas: 12,
        tipo: "D",
        dBaixa: "2023-03-16",
        pago: 50.0
      },
      {
        id: 4,
        agrupamento: 1,
        nDoc: "0004",
        contato: "Bruno Arruda Magalhães",
        responsavel: "Susanna Sarah Cordeiro Paulino",
        valor: 100.0,
        vencimento: "2023-04-16",
        descricao: "Uma certa dívida",
        grupo: "Grupo A",
        subgrupo: "Subgrupo B",
        parcela: 4,
        tParcelas: 12,
        tipo: "D",
        dBaixa: null,
        pago: null
      },
      {
        id: 5,
        agrupamento: 1,
        nDoc: "0005",
        contato: "Bruno Arruda Magalhães",
        responsavel: "Susanna Sarah Cordeiro Paulino",
        valor: 100.0,
        vencimento: "2023-05-16",
        descricao: "Uma certa dívida",
        grupo: "Grupo A",
        subgrupo: "Subgrupo B",
        parcela: 5,
        tParcelas: 12,
        tipo: "D",
        dBaixa: null,
        pago: null
      },
      {
        id: 6,
        agrupamento: 1,
        nDoc: "0006",
        contato: "Bruno Arruda Magalhães",
        responsavel: "Susanna Sarah Cordeiro Paulino",
        valor: 100.0,
        vencimento: "2023-06-16",
        descricao: "Uma certa dívida",
        grupo: "Grupo A",
        subgrupo: "Subgrupo B",
        parcela: 6,
        tParcelas: 12,
        tipo: "D",
        dBaixa: null,
        pago: null
      },
      {
        id: 7,
        agrupamento: 1,
        nDoc: "0007",
        contato: "Bruno Arruda Magalhães",
        responsavel: "Susanna Sarah Cordeiro Paulino",
        valor: 100.0,
        vencimento: "2023-07-16",
        descricao: "Uma certa dívida",
        grupo: "Grupo A",
        subgrupo: "Subgrupo B",
        parcela: 7,
        tParcelas: 12,
        tipo: "D",
        dBaixa: null,
        pago: null
      },
      {
        id: 8,
        agrupamento: 1,
        nDoc: "0008",
        contato: "Bruno Arruda Magalhães",
        responsavel: "Susanna Sarah Cordeiro Paulino",
        valor: 100.0,
        vencimento: "2023-08-16",
        descricao: "Uma certa dívida",
        grupo: "Grupo A",
        subgrupo: "Subgrupo B",
        parcela: 8,
        tParcelas: 12,
        tipo: "D",
        dBaixa: null,
        pago: null
      },
      {
        id: 9,
        agrupamento: 1,
        nDoc: "0009",
        contato: "Bruno Arruda Magalhães",
        responsavel: "Susanna Sarah Cordeiro Paulino",
        valor: 100.0,
        vencimento: "2023-09-16",
        descricao: "Uma certa dívida",
        grupo: "Grupo A",
        subgrupo: "Subgrupo B",
        parcela: 9,
        tParcelas: 12,
        tipo: "D",
        dBaixa: null,
        pago: null
      },
      {
        id: 10,
        agrupamento: 1,
        nDoc: "0010",
        contato: "Bruno Arruda Magalhães",
        responsavel: "Susanna Sarah Cordeiro Paulino",
        valor: 100.0,
        vencimento: "2023-10-16",
        descricao: "Uma certa dívida",
        grupo: "Grupo A",
        subgrupo: "Subgrupo B",
        parcela: 10,
        tParcelas: 12,
        tipo: "D",
        dBaixa: null,
        pago: null
      },
      {
        id: 11,
        agrupamento: 1,
        nDoc: "0011",
        contato: "Bruno Arruda Magalhães",
        responsavel: "Susanna Sarah Cordeiro Paulino",
        valor: 100.0,
        vencimento: "2023-11-16",
        descricao: "Uma certa dívida",
        grupo: "Grupo A",
        subgrupo: "Subgrupo B",
        parcela: 11,
        tParcelas: 12,
        tipo: "D",
        dBaixa: null,
        pago: null
      },
      {
        id: 12,
        agrupamento: 1,
        nDoc: "0012",
        contato: "Bruno Arruda Magalhães",
        responsavel: "Susanna Sarah Cordeiro Paulino",
        valor: 100.0,
        vencimento: "2023-12-16",
        descricao: "Uma certa dívida",
        grupo: "Grupo A",
        subgrupo: "Subgrupo B",
        parcela: 12,
        tParcelas: 12,
        tipo: "D",
        dBaixa: null,
        pago: null
      }
]